name: flutter_recaptcha_enterprise
description: Flutter Google Recaptcha Enterprise
version: 0.1.0
repository: https://github.com/tapeo/flutter_recaptcha_enterprise

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: it.matteoricupero.flutter_recaptcha_enterprise
        pluginClass: FlutterRecaptchaEnterprisePlugin
      ios:
        pluginClass: FlutterRecaptchaEnterprisePlugin
